baseUrl_companies = "https://restapi.tech/api/companies"
baseUrl_users = "https://restapi.tech/api/users"
baseUrl_issues_companies = "https://restapi.tech/api/issues/companies"
baseUrl_issues_users = "https://restapi.tech/api/issues/users"
baseUrl_auth = " когда доберемся, тогда придумаем как это оформить. Не помню, сколько там тестов"
